### ISSUE TITLE
Move template rendering to a separate method

### ISSUE THREAD

**Issue by KommuSoft** [ambient-innovation/django-pony-express#21]
It probably makes more sense to move https://github.com/ambient-innovation/django-pony-express/blob/6908aff84dd52afa94f7c32442c32921ef235058/django_pony_express/services/base.py#L248 to a separate method.

This makes it possible *not* to render a template, or probably more useful, work with a *dynamically* generated `Template`.

**Comment by GitRon** [comment]
Hi @KommuSoft! Thx for the input, makes total sense 👌  Do you want to contribute on this one? Otherwise, I'll put it on my list and fix it in the near future.

**Comment by KommuSoft** [comment]
Yes, I will try to create a PR for this :).

**Comment by GitRon** [comment]
Fixed 👌  Thx for all your effort @KommuSoft!

**Comment by GitRon** [comment]
New release: https://pypi.org/project/django-pony-express/2.4.3/
